fix update deployment

diff --git a/.tekton/update-deployment.yaml b/.tekton/update-deployment.yaml
--- a/.tekton/update-deployment.yaml
+++ b/.tekton/update-deployment.yaml
@@ -33,7 +33,6 @@ spec:
       - name: PARAM_IMAGE
         value: $(params.image)
     script: |
-      set -x
       if test -f /gitops-auth-secret/password ; then
         gitops_repo_url=${PARAM_GITOPS_REPO_URL}
         remote_without_protocol=${gitops_repo_url#'https://'}
@@ -47,7 +46,12 @@ spec:
           origin_with_auth=https://${password}@${remote_without_protocol}.git
         fi
       else
-        echo "git credentials to push into gitops repository ${PARAM_GITOPS_REPO_URL} is not configured."
+        echo "git credentials to push into gitops repository if [ $? -ne 0 ]; then
+          note='Failed to download roxctl'
+          echo $note
+          set_test_output_result ERROR "$note"
+          exit 1
+        fi is not configured."
         echo "gitops repository is not updated automatically."
         echo "You can update gitops repository with the new image: ${PARAM_IMAGE} manually"
         echo "TODO: configure git credentials to update gitops repository."
@@ -70,4 +74,9 @@ spec:
       git add .
       git commit -m "Update '${component_id}' component image to: ${PARAM_IMAGE}"
       git remote set-url origin $origin_with_auth
-      git push
+      git push 2> /dev/null || \
+      {
+        echo "Failed to push update to gitops repository: ${PARAM_GITOPS_REPO_URL}"
+        echo 'Do you have correct git credentials configured?'
+        exit 1
+      }
